name: Find tab

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: find tab in file
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD~ HEAD)
          echo "$CHANGED_FILES" | while read files
          do
          TAB_FILES=$(grep $'\t' $files)
          echo "In the modified file '$files' found line with tab '$TAB_FILES'" >report.log
          done
